In [ ]:
!gdown 1UPyrvIqB-UCyqGR8wq3IJJsc7ClxQMeZ

Downloading...
From: https://drive.google.com/uc?id=1UPyrvIqB-UCyqGR8wq3IJJsc7ClxQMeZ
To: /content/amazon_stock_price.csv
100% 414k/414k [00:00<00:00, 12.3MB/s]

In [ ]:
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

In [ ]:
data = pd.read_csv('amazon_stock_price.csv')

In [ ]:
data

            date      open      high       low     close      volume
0     1997-05-15    0.1219    0.1250    0.0964    0.0979  1443120000
1     1997-05-16    0.0984    0.0990    0.0854    0.0865   294000000
2     1997-05-19    0.0880    0.0885    0.0812    0.0854   122136000
3     1997-05-20    0.0865    0.0875    0.0818    0.0818   109344000
4     1997-05-21    0.0818    0.0823    0.0688    0.0714   377064000
...          ...       ...       ...       ...       ...         ...
6680  2023-11-30  144.7600  146.9300  144.3300  146.0900    65814000
6681  2023-12-01  146.0000  147.2500  145.5500  147.0300    39924600
6682  2023-12-04  145.2500  145.3500  142.8100  144.8400    48294200
6683  2023-12-05  143.5500  148.5700  143.1300  146.8800    46822400
6684  2023-12-06  147.5800  147.8500  144.2800  144.5200    39603800

[6685 rows x 6 columns]

In [ ]:
data.isnull().sum()

date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [ ]:
data['date'] = pd.to_datetime(data['date'])

In [ ]:
data = data.set_index('date')

In [ ]:
lags = 5

In [ ]:
for i in range(1, lags + 1):
  data[f'close_prev_{i}'] = data['close'].shift(i)

In [ ]:
data

,open,high,low,close,volume,close_prev_1,close_prev_2,close_prev_3,close_prev_4,close_prev_5
date,,,,,,,,,,
1997-05-15,0.1219,0.1250,0.0964,0.0979,1443120000,NaN,NaN,NaN,NaN,NaN
1997-05-16,0.0984,0.0990,0.0854,0.0865,294000000,0.0979,NaN,NaN,NaN,NaN
1997-05-19,0.0880,0.0885,0.0812,0.0854,122136000,0.0865,0.0979,NaN,NaN,NaN
1997-05-20,0.0865,0.0875,0.0818,0.0818,109344000,0.0854,0.0865,0.0979,NaN,NaN
1997-05-21,0.0818,0.0823,0.0688,0.0714,377064000,0.0818,0.0854,0.0865,0.0979,NaN
...,...,...,...,...,...,...,...,...,...,...
2023-11-30,144.7600,146.9300,144.3300,146.0900,65814000,146.3200,147.0300,147.7300,146.7400,146.71
2023-12-01,146.0000,147.2500,145.5500,147.0300,39924600,146.0900,146.3200,147.0300,147.7300,146.74
2023-12-04,145.2500,145.3500,142.8100,144.8400,48294200,147.0300,146.0900,146.3200,147.0300,147.73
2023-12-05,143.5500,148.5700,143.1300,146.8800,46822400,144.8400,147.0300,146.0900,146.3200,147.03
2023-12-06,147.5800,147.8500,144.2800,144.5200,39603800,146.8800,144.8400,147.0300,146.0900,146.32

In [ ]:
data.isnull().sum()

open            0
high            0
low             0
close           0
volume          0
close_prev_1    1
close_prev_2    2
close_prev_3    3
close_prev_4    4
close_prev_5    5
dtype: int64

In [ ]:
data = data.dropna(axis=0)

In [ ]:
features = [f'close_prev_{i}' for i in range(1, lags + 1)]

In [ ]:
X, Y = data[features], data['close']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, shuffle=False)

In [ ]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
Y_train = scaler.fit_transform(Y_train.values.reshape(-1, 1))

In [ ]:
X_train.shape

(5344, 5)

In [ ]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)

In [ ]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

In [ ]:
X_train.shape

(5344, 5, 1)